//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int ID { get; set; }
        public int CandidateID { get; set; }
        public int SubjectID { get; set; }
        public Nullable<decimal> Mark { get; set; }
    
        public virtual Candidates Candidates { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
