//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public int ID { get; set; }
        public int CandidateID { get; set; }
        public int MajorCombinationID1 { get; set; }
        public int MajorCombinationID2 { get; set; }
        public int MajorCombinationID3 { get; set; }
        public int MajorCombinationID4 { get; set; }
    
        public virtual Candidates Candidates { get; set; }
        public virtual MajorCombinations MajorCombinations { get; set; }
        public virtual MajorCombinations MajorCombinations1 { get; set; }
        public virtual MajorCombinations MajorCombinations2 { get; set; }
        public virtual MajorCombinations MajorCombinations3 { get; set; }
    }
}
