//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combinations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Combinations()
        {
            this.MajorCombinations = new HashSet<MajorCombinations>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SubjectID1 { get; set; }
        public Nullable<int> SubjectID2 { get; set; }
        public Nullable<int> SubjectID3 { get; set; }
        public Nullable<int> MainSubjectID { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Subjects Subjects1 { get; set; }
        public virtual Subjects Subjects2 { get; set; }
        public virtual Subjects Subjects3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MajorCombinations> MajorCombinations { get; set; }
    }
}
