//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiary> Beneficiaries { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<MajorSubjectCombination> MajorSubjectCombinations { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SubjectCombination> SubjectCombinations { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    }
}
