//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int ID { get; set; }
        public int CandidateID { get; set; }
        public int SubjectID { get; set; }
        public decimal Score { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
