//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int ID { get; set; }
        public int CandidateID { get; set; }
        public int MajorCombinationID1 { get; set; }
        public int MajorCombinationID2 { get; set; }
        public int MajorCombinationID3 { get; set; }
        public int MajorCombinationID4 { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual MajorSubjectCombination MajorSubjectCombination { get; set; }
        public virtual MajorSubjectCombination MajorSubjectCombination1 { get; set; }
        public virtual MajorSubjectCombination MajorSubjectCombination2 { get; set; }
        public virtual MajorSubjectCombination MajorSubjectCombination3 { get; set; }
    }
}
