//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportView
    {
        public int ID { get; set; }
        public string CandidateID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<decimal> CutOff { get; set; }
        public Nullable<int> BeneficiaryID { get; set; }
        public string BeneficiaryName { get; set; }
        public bool HasPrivilege { get; set; }
        public string MajorName { get; set; }
    }
}
